name: iPhone Simulator Test

on: [push, pull_request]

jobs:
  build:
    name: flutter drive
    runs-on: macOS-10.14
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: flutter test
        run: flutter drive --target=test_driver/app.dart
